[pytest]
minversion = 7.0
addopts = -v -ra --strict-markers
testpaths = tests
pythonpath = .

log_cli = true
log_cli_level = INFO

markers =
    smoke: быстрые проверки
    regression: регрессия
    login: Login Form
    textbox: Text Box
    registration: Student Registration Form
    unit: без браузера (теория параметризации)
    desktop: десктопный viewport
    mobile: мобильный viewport
