[pytest]
minversion = 7.0
addopts = -v -ra --strict-markers
testpaths = tests
pythonpath = .

log_cli = true
log_cli_level = INFO

markers =
    smoke: быстрые критические проверки
    regression: расширенные регрессионные сценарии
    login: тесты формы Login
    textbox: тесты Text Box
    unit: юнит-тесты без браузера
